AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Local configuration for the SierraUpdatePoller function'

Globals:
  Function:
    Timeout: 300
    Runtime: python3.9
    Handler: main.handler
    Environment:
      Variables:
        LOG_LEVEL: debug
        S3_AWS_REGION: us-east-1
        NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com
        PLATFORM_API_BASE_URL: https://dev-platform.nypl.org/api/v0.1/
        BUCKET_NAME: nypl-github-actions-builds-qa

Resources:
  M2CustomerCodeStore:
    Type: AWS::Serverless::Function
