---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
ENCRYPTED_VARIABLES:
    REDIS_ENDPOINT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJYwgZMGCSqGSIb3DQEHBqCBhTCBggIBADB9BgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMqYVOCL/lu0a2PNXQIBEIBQkRpOGbs97tQbq1yEcy/oKv9H2KU5eAWKvRP3DJgtlujGaA7oxYzC/o/5QNhebUKHrfwVeDC16mh9vttvgSlnTZml2Q/FINRYpVhzh4XBOvM=
...