---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
ENCRYPTED_VARIABLES:
    REDIS_ENDPOINT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAI8wgYwGCSqGSIb3DQEHBqB/MH0CAQAweAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzAZ9Dp40E4jmc6KMYCARCAS8Itbor+w3p13pG31l8WWF3Vi8dbzPY9R8EvWMr/oZynBhMRz/ybua3s2SYR/146J/rQSHWr5ALL+ls6OmsAIDAmL2rAy+ptZU5nKg==

...