---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
ENCRYPTED_VARIABLES:
    REDIS_ENDPOINT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJ0wgZoGCSqGSIb3DQEHBqCBjDCBiQIBADCBgwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxCkYXWIZwu6C3Oh3wCARCAVuH0ZHQ7M1+gZTh/HIsIf4oNCQ93QHkrUs1UnFRtCr8pMkrPhumKd8jYS5JdoND1XlzddeSxL8ZyG9yHRlhMiU4X/E92PKQnjj/mYFq5skWIKfrCV7j1
...