---
PLAINTEXT_VARIABLES:
  AWS_REGION: us-east-1
  LOG_LEVEL: debug
ENCRYPTED_VARIABLES:
  REDIS_ENDPOINT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJIwgY8GCSqGSIb3DQEHBqCBgTB/AgEAMHoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDWX9BIN1gH0OGiO2AgEQgE2ANuvYL8j3xy894MN6kvuotyeu3t1MVu7BhnPNOvoHiG4THJ9Z2uq3faTJrKx47nXhTFqgISz4iuDAA6POoA5Bu5vWl/WTRQnQuOvYhw==
...
